# Python, NumPy and Vectorization

In [11]:
import numpy as np
import time

In [4]:
"""
    Python is the programming language we will be using in this course. 
    It has a set of numeric data types and arithmetic operations. 
    NumPy is a library that extends the base capabilities of python to add 
    a richer data set including more numeric types, vectors, matrices, 
    and many matrix functions. NumPy and python  work together fairly seamlessly. 
    Python arithmetic operators work on NumPy data types and many NumPy 
    functions will accept python data types.
"""

'\n    Python is the programming language we will be using in this course. \n    It has a set of numeric data types and arithmetic operations. \n    NumPy is a library that extends the base capabilities of python to add \n    a richer data set including more numeric types, vectors, matrices, \n    and many matrix functions. NumPy and python  work together fairly seamlessly. \n    Python arithmetic operators work on NumPy data types and many NumPy \n    functions will accept python data types.\n'

In [13]:
# Vectir Creation
a = np.zeros(4)
print(f"Vector a: {a}, a shape: {a.shape}, a data type: {a.dtype}")
a = np.zeros((4,))
print(f"Vector a: {a}, a shape: {a.shape}, a data type: {a.dtype}")
a = np.random.random_sample(4)
print(f"Vector a: {a}, a shape: {a.shape}, a data type: {a.dtype}")

Vector a: [0. 0. 0. 0.], a shape: (4,), a data type: float64
Vector a: [0. 0. 0. 0.], a shape: (4,), a data type: float64
Vector a: [0.13708898 0.67937309 0.3854687  0.17010676], a shape: (4,), a data type: float64


In [16]:
a = np.arange(4.) 
print(f"np.arange(4.) a: {a}, a shape: {a.shape}, a data type: {a.dtype}")
a = np.random.rand(4)
print(f"np.random.rand(4) a: {a}, a shape: {a.shape}, a data type: {a.dtype}")


np.arange(4.) a: [0. 1. 2. 3.], a shape: (4,), a data type: float64
np.random.rand(4) a: [0.00626936 0.73895155 0.61720483 0.63066938], a shape: (4,), a data type: float64


In [18]:
a = np.array([5,4,3,2])
print(f"np.array([5,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5., 4., 3., 2.])
print(f"np.array([5., 4., 3., 2.]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]): a = [5 4 3 2], a shape = (4,), a data type = int64
np.array([5., 4., 3., 2.]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [19]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


Operations on Vectors 

Indexing means referring to an element of an array by its position within the array.
Slicing means getting a subset of elements from an array based on their indices.

In [20]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

# indec must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

    

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


In [21]:
# Vector Slicing
a = np.arange(10)
print(f"a = {a}")

# access 5 consecutive elements (start:stop:step)
c = a[2:7:1]
print(f"a[2:7:1] = {c}")

#access 3 elements separated by 2 elements
c = a[2:7:2]
print(f"a[2:7:2] = {c}")

# access all elements index 3 and above
c = a[3:]
print(f"a[3:] = {c}")

# access all elements up to index 3
c = a[:3]
print(f"a[:3] = {c}")

# access all elements
c = a[:]
print(f"a[:] = {c}")



a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


In [23]:
# single vector operations
a = np.array([1,2,3,4])
print(f"a = {a}")

# negative of a
b = -a
print(f"b = -a = {b}")

# sum all elements of a
b = np.sum(a)
print(f"b = np.sum(a) = {b}")

# mean of all elements of a
b = np.mean(a)
print(f"b = np.mean(a) = {b}")

b = a**2
print(f"b = a**2 = {b}")

a = [1 2 3 4]
b = -a = [-1 -2 -3 -4]
b = np.sum(a) = 10
b = np.mean(a) = 2.5
b = a**2 = [ 1  4  9 16]


In [24]:
# Vector element-wise operations 
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, -3, -4])  
print(f" Binary operations on vectors a and b: {a+b}")


 Binary operations on vectors a and b: [0 0 0 0]


In [25]:
# try mismatched vector sizes
c = np.array([1, 2, 3])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)    

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (3,) 


In [26]:
a = np.array([1, 2, 3, 4])

# multiply each element of a by 5 
b = 5 * a
print(f"b = 5 * a = {b}")

b = 5 * a = [ 5 10 15 20]


In [27]:
# vector dot product
# The dot product multiplies the values in two vectors element-wise and then sums the result
# Vector dot product requires the dimensions of the two vectors to be the same.

def my_dot(a,b):
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x += a[i]*b[i]
        return x
    
    


In [28]:
# test 1-D dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# compute the dot 
c = my_dot(a,b)
print(f"my_dot(a,b) = {c}")

my_dot(a,b) = 4


In [29]:
# using NumPy dot function
c = np.dot(a,b)
print(f"np.dot(a,b) = {c}")
c = np.dot(b,a)
print(f"np.dot(b,a) = {c}")

np.dot(a,b) = 32
np.dot(b,a) = 32


We utilized the NumPy library because it improves speed memory efficiency. Let's demonstrate:

In [31]:
# check the time to run numpyy dot function vs my_dot function
a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time() # capture the start time
c = np.dot(a,b)
toc = time.time() # capture the end time

print(f"Time to run np.dot(a,b): {1000*(toc-tic): .4f} milli-seconds")

tic = time.time() # capture the start time
c = my_dot(a,b)
toc = time.time() # capture the end time
print(f"Time to run my_dot(a,b): {1000*(toc-tic): .4f} milli-seconds")

# remove the big array from memory
del a
del b

Time to run np.dot(a,b):  3.5710 milli-seconds
Time to run my_dot(a,b):  0.0300 milli-seconds


In [36]:
# x_train has dimension (m,n), it is a 2 Dimentional array (2D)
# w will be a 1D array of dimension (n,)

X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot (X[1],w)

print(f"X has shape {X.shape}")
print(f"X[1] has shape {X[1].shape} and w has shape {w.shape}")
print(f"np.dot(X[1],w) = {c}")
print(f"c has shape {c.shape}") # c is a scalar

X has shape (4, 1)
X[1] has shape (1,) and w has shape (1,)
np.dot(X[1],w) = 4
c has shape ()


In [47]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}") 

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample(3)  
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 3))  
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.rand(3)
print(f"a shape = {a.shape}, a = {a}")

a = np.random.rand(3,1)
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (3,), a = [0.16078629 0.81921534 0.63204929]
a shape = (1, 3), a = [[0.14174901 0.12918824 0.23228821]]
a shape = (3,), a = [0.52479294 0.70632828 0.27752811]
a shape = (3, 1), a = [[0.7448111 ]
 [0.46423901]
 [0.85310557]]


In [37]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [48]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


Reshape

The previous example used reshape to shape the array.
a = np.arange(6).reshape(-1, 2)
This line of code first created a 1-D Vector of six elements. It then reshaped that vector into a 2-D array using the reshape command. This could have been written:
a = np.arange(6).reshape(3, 2)
To arrive at the same 3 row, 2 column array. The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.

In [54]:
# vector 2-D slicing operations 
a = np.arange(20).reshape(-1,10)
print(f"a = {a}")

# access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")

# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
